### ISSUE TITLE
Export Sessions

### ISSUE THREAD

**Issue by anirudhvarma12** [anirudhvarma12/rabbit-hole-webext#3]
The idea is that users should be able to export sessions and view them through some kind of viewer so that they can own their data easily.

For this feature to make sense, we need to develop the viewer separately so users can either host it themselves, maybe wrap it in electron app so that they can use their graphs even outside the browser

**Comment by Thomashighbaugh** [comment]
That would be really awesome, if I get some time this week I might look into how to do this myself. If I find anything on how to do it I let you know or if its trivial to implement I will submit a pull request. 

I really (like REALLY) love this extension, its very helpful to go back through some of my crazy research binges on wikipedia with this awesome extension. Thank you for the great work and keep it up.

**Comment by anirudhvarma12** [comment]
@Thomashighbaugh , thanks for the review and the help.

I was actually waiting for someone to come and ask for this as there are a bunch of formats that data can be exported to. I was thinking

1. Image
2. JSON with the plain data, relations and notes.
3. Formats for mind-mapping tools like Rome, Obsidian etc. (This needs research, but would be good to have I feel)

I'll try taking a stab at it over the weekend

**Comment by anirudhvarma12** [comment]
Hey @Thomashighbaugh , this feature has been published. You can now export to images + get the raw json data.
